/**
* @author <Your Name> <Your e-mail/Website if you would like>
* @license [MIT](http://www.opensource.org/licenses/mit-license.php)
*/
(function ($) {
	'use strict';

	$.sceditor.locale["pt-BR"] = {
		"Bold": "Negrito",
		"Italic": "ItÃ¡lico",
		"Underline": "Sublinhado",
		"Strikethrough": "Rasurado",
		"Subscript": "Subscrito",
		"Superscript": "Sobrescrito ",
		"Align left": "Alinhar Ã  esquerda",
		"Center": "Centralizar",
		"Align right": "Alinhar Ã  direita",
		"Justify": "Justificar",
		"Font Name": "Nome da fonte",
		"Font Size": "Tamanho da fonte",
		"Font Color": "Cor da fonte",
		"Remove Formatting": "Remover a formataÃ§Ã£o",
		"Cut": "Recortar",
		"Your browser does not allow the cut command. Please use the keyboard shortcut Ctrl/Cmd-X": "Seu navegador nÃ£o permite o comando recortar. Favor use o atalho Ctrl/Cmd-X",
		"Copy": "Copiar",
		"Your browser does not allow the copy command. Please use the keyboard shortcut Ctrl/Cmd-C": "Seu navegador nÃ£o permite o comando copiar. Favor use o atalho Ctrl/Cmd-C",
		"Paste": "Colar",
		"Your browser does not allow the paste command. Please use the keyboard shortcut Ctrl/Cmd-V": "Seu navegador nÃ£o permite o comando colar. Favor use o atalho Ctrl/Cmd-V",
		"Paste your text inside the following box:": "Cole o seu texto dentro da caixa de texto a seguir:",
		"Paste Text": "Colar o texto",
		"Bullet list": "Lista com marcadores",
		"Numbered list": "Lista numÃ©rica",
		"Undo": "Desfazer",
		"Redo": "Refazer",
		"Rows:": "Linhas:",
		"Cols:": "Colunas:",
		"Insert a table": "Inserir uma tabela",
		"Insert a horizontal rule": "Inserir uma linha horizontal",
		"Code": "CÃ³digo",
		"Width (optional):": "Largura (opcional):",
		"Height (optional):": "Altura (opcional):",
		"Insert an image": "Inserir uma imagem",
		"E-mail:": "E-mail:",
		"Insert an email": "Inserir um e-mail",
		"URL:": "URL:",
		"Insert a link": "Inserir um hiperlink",
		"Unlink": "Remover o hiperlink",
		"More": "Mais",
		"Insert an emoticon": "Inserir um emoticon",
		"Video URL:": "Video URL:",
		"Insert": "Inserir",
		"Insert a YouTube video": "Inserir YouTube video",
		"Insert current date": "Inserir a data atual",
		"Insert current time": "Inserir a hora atual",
		"Print": "Imprimir",
		"View source": "Fonte",
		"Description (optional):": "DescriÃ§Ã£o (opcional):",
		"Enter the image URL:": "Informe o endereÃ§o URL da imagem:",
		"Enter the e-mail address:": "Informe o endereÃ§o de e-mail:",
		"Enter the displayed text:": "Digite o texto exibido:",
		"Enter URL:": "Informe o endereÃ§o URL:",
		"Enter the YouTube video URL or ID:": "Informe o endereÃ§o URL do YouTube ou ID:",
		"Insert a Quote": "Inserir uma citaÃ§Ã£o",
		dateFormat: "day-month-year"
	}
})(jQuery);